### PR TITLE
Standalone command without docs-ts wrapper

### PR DESCRIPTION
**Pull request by thomasvargiu**
Since `docs-ts` calls `process.exit()` it should be better to release it as a standalone command to execute

### CODE REVIEW

**Review by gillchristian — COMMENTED** [review]
Nice work! It makes total sense :ok_hand: 

Could you please revert the changes of the `.gitignore` and add back the `yarn.lock` file? :pray:

**Comment by thomasvargiu** [comment]
Done, with some refactoring to remove deprecated statements.
The README is changed by `prettier`

**Comment by gillchristian** [comment]
Thanks!

Will add some changes form my side and make a release

**Comment by gillchristian** [comment]
@thomasvargiu published `v0.0.2`, thanks again!

**Pull request merged**
